# Generated by Django 5.2.6 on 2025-09-08 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shift', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shiftexception',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='shiftexception',
            name='exception_type',
            field=models.CharField(choices=[('once', 'Chỉ 1 ngày'), ('permanent', 'Cố định')], default='once', max_length=20),
        ),
        migrations.AddField(
            model_name='shiftexception',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shift.shift'),
        ),
        migrations.AlterField(
            model_name='shiftexception',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
