# Generated by Django 5.2.6 on 2025-09-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shift', '0002_alter_shiftexception_unique_together_and_more'),
        ('employee', '0003_employee_user_alter_employee_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftexception',
            name='is_added',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shiftexception',
            name='exception_type',
            field=models.CharField(choices=[('once', 'Chỉ 1 ngày'), ('permanent', 'Cố định')], default='once', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='shiftexception',
            unique_together={('employee', 'date', 'exception_type')},
        ),
    ]
