# Generated by Django 5.2.6 on 2025-09-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shift', '0003_shiftexception_is_added_and_more'),
        ('employee', '0003_employee_user_alter_employee_gender'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shiftexception',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='shiftexception',
            name='weekday',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True),
        ),
        migrations.AlterUniqueTogether(
            name='shiftexception',
            unique_together={('employee', 'date', 'weekday', 'exception_type')},
        ),
    ]
