# Generated by Django 5.1.1 on 2025-09-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shift', '0004_alter_shiftexception_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='shift',
            name='qr_token',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
