# Generated by Django 5.1.1 on 2025-09-20 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shift', '0005_shift_qr_code_shift_qr_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='qr_code',
        ),
    ]
