# Generated by Django 5.2.6 on 2025-10-03 01:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Attendance", "0002_remove_attendance_wifi_ssid"),
        ("employee", "0005_alter_employee_position_employeeface"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Tên loại chi phí"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang sử dụng"),
                ),
            ],
            options={
                "verbose_name": "Loại chi phí",
                "verbose_name_plural": "Các loại chi phí",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255, verbose_name="Mô tả")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Số tiền"
                    ),
                ),
                (
                    "expense_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Ngày chi"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Chờ duyệt"),
                            ("approved", "Đã duyệt"),
                            ("rejected", "Từ chối"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "receipt_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="expenses/receipts/",
                        verbose_name="Hóa đơn/Chứng từ",
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, null=True, verbose_name="Ghi chú"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Cập nhật lần cuối"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_expenses",
                        to="employee.employee",
                        verbose_name="Người phê duyệt",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_expenses",
                        to="employee.employee",
                        verbose_name="Người tạo",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="finance.expensecategory",
                        verbose_name="Loại chi phí",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chi phí",
                "verbose_name_plural": "Danh sách chi phí",
                "ordering": ["-expense_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PayrollSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payroll_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Mã bảng lương",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Ngày bắt đầu kỳ lương")),
                ("end_date", models.DateField(verbose_name="Ngày kết thúc kỳ lương")),
                (
                    "total_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Tổng số giờ làm",
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Lương theo giờ (VND)",
                    ),
                ),
                (
                    "base_salary",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Tiền công (total_hours × hourly_rate)",
                    ),
                ),
                (
                    "bonus",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Tiền thưởng",
                    ),
                ),
                (
                    "advance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Tiền ứng trước",
                    ),
                ),
                (
                    "deduction",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Khấu trừ/phạt",
                    ),
                ),
                (
                    "net_salary",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Lương thực nhận",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Nháp"),
                            ("pending", "Chờ duyệt"),
                            ("approved", "Đã duyệt"),
                            ("paid", "Đã thanh toán"),
                            ("cancelled", "Đã hủy"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ngày duyệt"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Ghi chú"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ngày lập bảng lương"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Cập nhật lần cuối"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_payrolls",
                        to="employee.employee",
                        verbose_name="Người duyệt",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_payrolls",
                        to="employee.employee",
                        verbose_name="Người lập",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_summaries",
                        to="employee.employee",
                        verbose_name="Nhân viên",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bảng lương tổng",
                "verbose_name_plural": "Danh sách bảng lương",
                "ordering": ["-start_date", "-created_at"],
                "unique_together": {("employee", "start_date", "end_date")},
            },
        ),
        migrations.CreateModel(
            name="PayrollDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_date", models.DateField(verbose_name="Ngày làm việc")),
                (
                    "check_in_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="Giờ vào"),
                ),
                (
                    "check_out_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="Giờ ra"),
                ),
                (
                    "hours_worked",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Số giờ làm",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Bình thường"),
                            ("T", "Trễ"),
                            ("S", "Ra sớm"),
                            ("V", "Vắng"),
                            ("TS", "Trễ + Ra sớm"),
                        ],
                        default="",
                        max_length=10,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, null=True, verbose_name="Ghi chú"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "attendance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payroll_details",
                        to="Attendance.attendance",
                        verbose_name="Bản ghi chấm công",
                    ),
                ),
                (
                    "payroll_summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_details",
                        to="finance.payrollsummary",
                        verbose_name="Bảng lương tổng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chi tiết bảng lương",
                "verbose_name_plural": "Chi tiết bảng lương",
                "ordering": ["work_date"],
            },
        ),
        migrations.CreateModel(
            name="Revenue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=255, verbose_name="Nguồn thu")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Số tiền"
                    ),
                ),
                (
                    "revenue_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Ngày thu"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sales", "Doanh thu bán hàng"),
                            ("service", "Dịch vụ"),
                            ("other", "Khác"),
                        ],
                        default="sales",
                        max_length=20,
                        verbose_name="Loại doanh thu",
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, null=True, verbose_name="Ghi chú"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Cập nhật lần cuối"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_revenues",
                        to="employee.employee",
                        verbose_name="Người ghi nhận",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doanh thu",
                "verbose_name_plural": "Danh sách doanh thu",
                "ordering": ["-revenue_date", "-created_at"],
            },
        ),
    ]
