# Generated by Django 5.2.6 on 2025-09-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('position', models.CharField(choices=[('Manager', 'Quản lý'), ('Cashier', 'Thu ngân'), ('Barista', 'Pha chế'), ('Waiter', 'Phục vụ'), ('Cleaner', 'Tạp vụ'), ('Security', 'Bảo vệ')], max_length=50)),
                ('joining_date', models.DateField()),
                ('mobile_number', models.CharField(max_length=10)),
                ('employee_image', models.ImageField(blank=True, upload_to='employees/')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
    ]
