# Generated by Django 5.1.1 on 2025-09-09 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_user_alter_employee_gender'),
    ]

    operations = [
    ]
