# Generated by Django 5.2.6 on 2025-09-28 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0004_update_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.CharField(
                choices=[
                    ("Manager", "quin lý"),
                    ("Cashier", "Thu ngân"),
                    ("Barista", "Pha chế"),
                    ("Waiter", "Phục vụ"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="EmployeeFace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("face_image", models.ImageField(upload_to="employee_faces/")),
                ("face_encoding", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faces",
                        to="employee.employee",
                    ),
                ),
            ],
        ),
    ]
