# Generated by Django 5.1.1 on 2025-09-09 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Shift', '0004_alter_shiftexception_unique_together_and_more'),
        ('employee', '0004_update_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_note', models.CharField(blank=True, max_length=255, null=True)),
                ('face_image', models.ImageField(blank=True, null=True, upload_to='attendance_faces/')),
                ('face_verified', models.BooleanField(default=False)),
                ('unique_token', models.CharField(editable=False, max_length=100, unique=True)),
                ('method', models.CharField(choices=[('auto', 'Tự động (FaceID + GPS)'), ('manual', 'Thủ công (Admin nhập)')], default='auto', max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shift.weeklyshiftassignment')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employee.employee')),
                ('exception', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shift.shiftexception')),
                ('manual_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_attendances', to='employee.employee')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shift.shift')),
            ],
            options={
                'verbose_name': 'Chấm công',
                'verbose_name_plural': 'Danh sách chấm công',
                'ordering': ['-created_at'],
            },
        ),
    ]
