# Generated by Django 5.2.6 on 2025-09-28 15:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Shift", "0006_remove_shift_qr_code"),
        ("employee", "0005_alter_employee_position_employeeface"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                (
                    "unique_token",
                    models.CharField(
                        default=uuid.uuid4, editable=False, max_length=100, unique=True
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "distance_meters",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                (
                    "location_note",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("wifi_ssid", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "face_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="attendance_faces/"
                    ),
                ),
                ("face_verified", models.BooleanField(default=False)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("auto", "Tự động (FaceID + GPS)"),
                            ("manual", "Thủ công (Admin nhập)"),
                        ],
                        default="auto",
                        max_length=10,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Shift.weeklyshiftassignment",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="employee.employee",
                    ),
                ),
                (
                    "exception",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Shift.shiftexception",
                    ),
                ),
                (
                    "manual_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manual_attendances",
                        to="employee.employee",
                    ),
                ),
                (
                    "matched_face",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employee.employeeface",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Shift.shift",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chấm công",
                "verbose_name_plural": "Danh sách chấm công",
                "ordering": ["-created_at"],
            },
        ),
    ]
