# Generated by Django 5.2.6 on 2025-09-30 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Attendance", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="wifi_ssid",
        ),
    ]
