# Generated by Django 5.2.6 on 2025-09-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0006_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='cKmP1YzcjqkI0ZLa3ggePDMeaJ7uebrg', editable=False, max_length=32, unique=True),
        ),
    ]
