# Generated by Django 5.2.6 on 2025-09-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0007_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_student',
            new_name='is_employee',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_teacher',
            new_name='is_manager',
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='ppjjfXzN2lOmVgL0a1fD7isl7O97Ix3b', editable=False, max_length=32, unique=True),
        ),
    ]
