# Generated by Django 5.1.1 on 2025-09-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0008_rename_is_student_customuser_is_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='eDHj8IG3B0ihlrHt3NupjbTpLmMIuELU', editable=False, max_length=32, unique=True),
        ),
    ]
