# Generated by Django 5.1.1 on 2025-09-05 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0009_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='qhvud62eeIw17PUXp7wY0RrSzCTfwQIC', editable=False, max_length=32, unique=True),
        ),
    ]
