# Generated by Django 5.1.1 on 2025-09-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0010_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='WvcnKXGHV7mi6xjJrMWo5rHnfcZevHHj', editable=False, max_length=32, unique=True),
        ),
    ]
