# Generated by Django 5.1.1 on 2025-09-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0011_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='d592VL3e4AXsUxN1tVJUORl3fnwRSpqj', editable=False, max_length=32, unique=True),
        ),
    ]
