# Generated by Django 5.2.6 on 2025-09-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_auth", "0013_alter_passwordresetrequest_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="token",
            field=models.CharField(
                default="mjFigA9vGpI1oxeJpCSFfiGN9FQHonSv",
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
    ]
